#ifndef HIGHLIGHTTYPE_H
#define HIGHLIGHTTYPE_H
enum HighLightType{

    FUNCTION,
    VERIABLE,
    OBJECT,
    COM,
    TYPE_DEFINE_INT,
    TYPE_DEFINE_FLOAT,
    TYPE_DEFINE_CHAR,
    TYPE_DEFINE_VOID,
    TYPE_DEIFNE_ENUM,
    TYPE_DEFINE_CLASS,
    TYPE_DEFINE_LONG,
    TYPE_DEFINE_BYTE,
    TYPE_DEFINE_DOUBLE,
    TYPE_DEFINE_SHORT,
    TYPE_DEFINE_UNSIGNED,
    TYPE_DEFINE_SIGNED,
    TYPE_DEFINE_AUTO,
    OPERATE_LEFT_SMALL_BRACE,
    OPERATE_RIGHT_SMALL_BRACE,
    OPERATE_LEFT_MID_BRACE,
    OPERATE_RIGHT_MID_BRACE,
    OPERATE_LEFT_BIG_BRACE,
    OPERATE_RIGHT_BIG_BRACE,
    OPERATE_EQUAL,
    OPERATE_GRATER,
    OPERATE_LESS
};
#endif // HIGHLIGHTTYPE_H
